backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img

collections:
  - label: 'News (English)'
    name: 'news_en'
    folder: 'gatsby/content/news/en'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    editor:
      preview: false
    filter: { field: 'language', value: 'en' }
    fields:
      - {
          label: 'Language',
          name: 'language',
          widget: 'select',
          options: ['en', 'es'],
        }
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: 'Description', name: 'description', widget: 'string' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
  - label: 'News (Español)'
    name: 'news_es'
    folder: 'gatsby/content/news/es'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    editor:
      preview: false
    filter: { field: 'language', value: 'es' }
    fields:
      - {
          label: 'Lenguaje',
          name: 'language',
          widget: 'select',
          options: ['en', 'es'],
        }
      - { label: 'Titulo', name: 'title', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: 'Description', name: 'description', widget: 'string' }
      - { label: 'Contenido', name: 'body', widget: 'markdown' }
